# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  build:
    docker:
      # specify the version
      - image: circleci/golang:1.9
    working_directory: /go/src/github.com/paulhovey/go-astar
    steps:
      - checkout

      # specify any bash command here prefixed with `run: `
      - run: if [ -n "$(go fmt ./...)" ]; then echo 'Code is not formatted with "go fmt"'; false; fi # fail if a .go file hasn't been formatted with gofmt
      - run: go vet ./... # go vet is the official Go static analyzer
      - run: go test -v ./... # run all the tests
      - run: go build ./... # make sure code builds